# require: rubocop-rails

# AllCops:
#   DisplayCopNames: true
#   NewCops: enable
#   TargetRubyVersion: 2.5
#   Include:
#     - '**/Gemfile'
#     - '**/Rakefile'
#     - '**/Appraisals'
#   Exclude:
#     - 'spec/dummy/**/*'
#     - 'lib/generators/**/*'

# Rails:
#   Enabled: true

# Metrics/LineLength:
#   Max: 150

# # DISABLED

# Style/Documentation:
#   Enabled: false

# Style/FrozenStringLiteralComment:
#   Enabled: false
